# Generated by Django 4.1.1 on 2022-09-13 21:11

from django.db import migrations, models
import django.db.models.deletion
import utils.mediapath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyersProfile',
            fields=[
                ('statusmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.statusmixin')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_no', models.IntegerField(blank=True)),
                ('address_line1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.ImageField(blank=True, upload_to=utils.mediapath.profile_image)),
            ],
            bases=('utils.statusmixin',),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('statusmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.statusmixin')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_no', models.IntegerField(blank=True)),
                ('address_line1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=utils.mediapath.profile_image)),
            ],
            bases=('utils.statusmixin',),
        ),
    ]
