# Generated by Django 4.1.1 on 2022-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('confirm_password', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
